version: '2.1'

services:

  prom:
    container_name: ivp-prom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
            - 9999:9090

  graphana:
    image: "grafana/grafana"
    ports:
      - 3000:3000
